# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - resume-reviewer

on:
  push:
    tags:
      - v*

env:
  # Repository secrets and variables
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  AZURE_PUBLISH_PROFILE: ${{ secrets.AzureAppService_PublishProfile_8f6b4448486f4c6cabd8886632b5bb31 }}

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Debug environment variables
      run: |
        echo "Docker username length: ${#DOCKER_USERNAME}"
        echo "Docker PAT length: ${#DOCKER_PAT}"
        if [ -z "$DOCKER_USERNAME" ]; then
          echo "❌ DOCKER_USERNAME is empty"
        else
          echo "✅ DOCKER_USERNAME is set"
        fi
        if [ -z "$DOCKER_PAT" ]; then
          echo "❌ DOCKER_PAT is empty"
        else
          echo "✅ DOCKER_PAT is set"
        fi

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: index.docker.io
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PAT }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ env.DOCKER_USERNAME }}/resumereviewer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'resume-reviewer'
        slot-name: 'Development'
        publish-profile: ${{ env.AZURE_PUBLISH_PROFILE }}
        images: 'index.docker.io/${{ env.DOCKER_USERNAME }}/resumereviewer:${{ github.sha }}'